name: Analyse

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.head_ref}}
          token: ${{secrets.RELEASE_IT}}
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: ./scripts/analyse.sh
      - run: echo ${{github.base_ref}}
      - run: echo ${{github.head_ref}}
